image: "python:3.7.6"

#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - pip install -r requirements.txt

# different stages in the pipeline
stages:
  - Test

pytest:
  stage: Test
  script:
  - cd Testing/;pytest -v