# Generated by Django 3.1.4 on 2020-12-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20201229_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='screen_name',
        ),
    ]
