# Generated by Django 3.0.5 on 2020-11-21 16:21

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default='')),
                ('claim', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField(default='')),
                ('content_type', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('raw_html', models.TextField(blank=True, default='')),
                ('title', models.TextField(blank=True, default='')),
                ('text_body', models.TextField(blank=True, default='')),
                ('cleaned_tokens', jsonfield.fields.JSONField()),
                ('html_links', jsonfield.fields.JSONField()),
            ],
        ),
    ]
