# Generated by Django 3.0.5 on 2020-11-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='favorite_count',
            field=models.TextField(default=''),
        ),
    ]
