# Generated by Django 3.0.5 on 2021-01-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_claim_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sentiment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
