# Generated by Django 3.0.5 on 2021-01-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='stance',
            field=models.TextField(blank=True, default=''),
        ),
    ]
