# Generated by Django 3.0.5 on 2020-11-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20201113_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='title',
        ),
    ]
